schema_version: 1

package:
  name: ralph-claude-code
  version: "0.9.9"

source:
  git: https://github.com/frankbria/ralph-claude-code.git
  rev: 509a9699a8c003dda8377be9f75e0af7f18ce94e

build:
  number: 5
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - mkdir -p "$PREFIX/share/ralph-claude-code"
        - mkdir -p "$PREFIX/share/ralph-claude-code/templates"
        - mkdir -p "$PREFIX/share/ralph-claude-code/lib"
        - cp "$SRC_DIR/install.sh" "$PREFIX/share/ralph-claude-code/install.sh"
        - cp "$SRC_DIR/ralph_loop.sh" "$PREFIX/share/ralph-claude-code/ralph_loop.sh"
        - cp "$SRC_DIR/ralph_monitor.sh" "$PREFIX/share/ralph-claude-code/ralph_monitor.sh"
        - cp "$SRC_DIR/ralph_import.sh" "$PREFIX/share/ralph-claude-code/ralph_import.sh"
        - cp "$SRC_DIR/setup.sh" "$PREFIX/share/ralph-claude-code/setup.sh"
        - cp "$SRC_DIR/create_files.sh" "$PREFIX/share/ralph-claude-code/create_files.sh"
        - chmod 755 "$PREFIX/share/ralph-claude-code/"*.sh
        - sed 's|\.\./templates/|$CONDA_PREFIX/share/ralph-claude-code/templates/|g' "$PREFIX/share/ralph-claude-code/setup.sh" > "$PREFIX/share/ralph-claude-code/setup.sh.tmp" && mv "$PREFIX/share/ralph-claude-code/setup.sh.tmp" "$PREFIX/share/ralph-claude-code/setup.sh" && chmod 755 "$PREFIX/share/ralph-claude-code/setup.sh"
        - cp -r "$SRC_DIR/templates/"* "$PREFIX/share/ralph-claude-code/templates/" || true
        - cp -r "$SRC_DIR/lib/"* "$PREFIX/share/ralph-claude-code/lib/" || true
        - |
          cat > "$PREFIX/bin/ralph" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          exec "$PREFIX_DIR/share/ralph-claude-code/ralph_loop.sh" "$@"
          EOF
        - |
          cat > "$PREFIX/bin/ralph-monitor" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          exec "$PREFIX_DIR/share/ralph-claude-code/ralph_monitor.sh" "$@"
          EOF
        - |
          cat > "$PREFIX/bin/ralph-setup" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          export CONDA_PREFIX="$PREFIX_DIR"
          exec "$PREFIX_DIR/share/ralph-claude-code/setup.sh" "$@"
          EOF
        - |
          cat > "$PREFIX/bin/ralph-import" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          exec "$PREFIX_DIR/share/ralph-claude-code/ralph_import.sh" "$@"
          EOF
        - chmod +x "$PREFIX/bin/ralph" "$PREFIX/bin/ralph-monitor" "$PREFIX/bin/ralph-setup" "$PREFIX/bin/ralph-import"

requirements:
  run:
    - git
    - jq

tests:
  - script:
      - if: unix
        then:
          - which ralph
          - test -x $PREFIX/bin/ralph

about:
  homepage: https://github.com/frankbria/ralph-claude-code
  license: MIT
  license_family: MIT
  summary: Autonomous AI development loop for Claude Code (legacy 0.9.9)
