schema_version: 1

package:
  name: ralph-claude-code
  version: "0.9.9"

source:
  git: https://github.com/frankbria/ralph-claude-code.git
  rev: 509a9699a8c003dda8377be9f75e0af7f18ce94e

build:
  number: 4
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - mkdir -p "$PREFIX/share/ralph-claude-code"
        - mkdir -p "$PREFIX/share/ralph-claude-code/templates"
        - mkdir -p "$PREFIX/share/ralph-claude-code/lib"
        # Install main executables (use cp + chmod for macOS compatibility)
        - cp "$SRC_DIR/install.sh" "$PREFIX/share/ralph-claude-code/install.sh"
        - cp "$SRC_DIR/ralph_loop.sh" "$PREFIX/share/ralph-claude-code/ralph_loop.sh"
        - cp "$SRC_DIR/ralph_monitor.sh" "$PREFIX/share/ralph-claude-code/ralph_monitor.sh"
        - cp "$SRC_DIR/ralph_import.sh" "$PREFIX/share/ralph-claude-code/ralph_import.sh"
        - cp "$SRC_DIR/setup.sh" "$PREFIX/share/ralph-claude-code/setup.sh"
        - cp "$SRC_DIR/create_files.sh" "$PREFIX/share/ralph-claude-code/create_files.sh"
        - chmod 755 "$PREFIX/share/ralph-claude-code/"*.sh
        # Patch setup.sh to use installed template paths instead of relative paths
        - sed -i 's|\.\./templates/|$CONDA_PREFIX/share/ralph-claude-code/templates/|g' "$PREFIX/share/ralph-claude-code/setup.sh"
        # Copy templates and lib directories
        - cp -r "$SRC_DIR/templates/"* "$PREFIX/share/ralph-claude-code/templates/" || true
        - cp -r "$SRC_DIR/lib/"* "$PREFIX/share/ralph-claude-code/lib/" || true
        # Create wrapper scripts in bin that work with both conda activate and pixi global
        - |
          cat > "$PREFIX/bin/ralph" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          exec "$PREFIX_DIR/share/ralph-claude-code/ralph_loop.sh" "$@"
          EOF
        - |
          cat > "$PREFIX/bin/ralph-monitor" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          exec "$PREFIX_DIR/share/ralph-claude-code/ralph_monitor.sh" "$@"
          EOF
        - |
          cat > "$PREFIX/bin/ralph-setup" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          export CONDA_PREFIX="$PREFIX_DIR"
          exec "$PREFIX_DIR/share/ralph-claude-code/setup.sh" "$@"
          EOF
        - |
          cat > "$PREFIX/bin/ralph-import" << 'EOF'
          #!/bin/bash
          SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
          PREFIX_DIR="${CONDA_PREFIX:-$(dirname "$SCRIPT_DIR")}"
          exec "$PREFIX_DIR/share/ralph-claude-code/ralph_import.sh" "$@"
          EOF
        - chmod +x "$PREFIX/bin/ralph" "$PREFIX/bin/ralph-monitor" "$PREFIX/bin/ralph-setup" "$PREFIX/bin/ralph-import"

requirements:
  run:
    # Note: bash is expected to be available on the system (standard unix tool)
    # git and jq are required from conda-forge for consistent behavior
    - git
    - jq

tests:
  - script:
      - if: unix
        then:
          - which ralph
          - which ralph-monitor
          - which ralph-setup
          - which ralph-import
          - test -x $PREFIX/bin/ralph
          - test -x $PREFIX/bin/ralph-monitor
          - test -x $PREFIX/bin/ralph-setup
          - test -x $PREFIX/bin/ralph-import
          - bash -n $PREFIX/share/ralph-claude-code/ralph_loop.sh
          - bash -n $PREFIX/share/ralph-claude-code/ralph_monitor.sh
          - bash -n $PREFIX/share/ralph-claude-code/ralph_import.sh
          - bash -n $PREFIX/share/ralph-claude-code/setup.sh

about:
  homepage: https://github.com/frankbria/ralph-claude-code
  license: MIT
  license_family: MIT
  summary: Autonomous AI development loop for Claude Code with intelligent exit detection
  description: |
    Ralph is an autonomous AI development framework that enables continuous development
    loops with Claude Code. It automates iterative improvements to projects with
    intelligent safeguards against infinite loops and API overuse.

    Key features:
    - Autonomous loops that execute Claude Code repeatedly until completion
    - Dual-condition exit detection requiring both completion indicators AND explicit EXIT_SIGNAL
    - Session continuity preserving context across iterations
    - Rate limiting with configurable hourly API call caps
    - Circuit breaker preventing runaway loops through advanced error detection
    - 5-hour API limit handling with user-prompted wait/exit options

    Commands provided:
    - ralph: Execute the autonomous development loop
    - ralph-monitor: Real-time monitoring dashboard
    - ralph-setup: Initialize new Ralph projects
    - ralph-import: Convert PRD documents to Ralph format

    Requirements:
    - Claude Code CLI (v2.0.76+)
    - Bash shell environment
    - tmux (optional, for integrated monitoring)
  documentation: https://github.com/frankbria/ralph-claude-code#readme
  repository: https://github.com/frankbria/ralph-claude-code

extra:
  recipe-maintainers:
    - blooop
