schema_version: 1

package:
  name: iterfzf
  version: "1.8.0.62.0"

source:
  # Platform-specific wheels from PyPI (iterfzf bundles fzf binaries)
  - url: https://files.pythonhosted.org/packages/df/37/4349484d7693324e40d51d0dc2f4d52b49b6765598e14af56642075ecdde/iterfzf-1.8.0.62.0-py3-none-manylinux_1_2_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl  # [linux and x86_64]
    sha256: 15094a8ac72d0755d3657333fcd72329ef2d79ea6633c37a6be27be66671ae48  # [linux and x86_64]
  - url: https://files.pythonhosted.org/packages/67/d5/16d76f04b23ecd4a2e98b112e73b10cfb058a4795a6e63d21df020d1c8cc/iterfzf-1.8.0.62.0-py3-none-manylinux_1_2_aarch64.manylinux_2_17_aarch64.manylinux2014_aarch64.whl  # [linux and aarch64]
    sha256: 24d5d658995be678a19c8ae633486daa9ef63fd17a2d759581c565885861817c  # [linux and aarch64]
  - url: https://files.pythonhosted.org/packages/ed/07/b43cd0d821e39d2d9afc03ca15d658f9c7aed7d8363bb95b2f35c22500bf/iterfzf-1.8.0.62.0-py3-none-macosx_10_7_x86_64.macosx_10_9_x86_64.whl  # [osx and x86_64]
    sha256: 057ac19b67128269a2c9efa7d419fef130d0df2210658d0e2fbe5a009b8b09e1  # [osx and x86_64]
  - url: https://files.pythonhosted.org/packages/e5/2b/0c9125d0500df4cec54fcc76a8db86fbffee65fbfdcf85b712231a431829/iterfzf-1.8.0.62.0-py3-none-macosx_11_0_arm64.whl  # [osx and arm64]
    sha256: e18ea2ccf4d572695987d90537977ef060ebf4157e783bb1a72a7f3fa1da2cd0  # [osx and arm64]
  - url: https://files.pythonhosted.org/packages/5b/0f/7169c67ba591917c9eb09ab5433cb6c8cc2346baee7b9abab9351da277a6/iterfzf-1.8.0.62.0-py3-none-win_amd64.whl  # [win and x86_64]
    sha256: b7cb95f93d5c1d901e8b7ccc886870f48f8331ebbba230cbd49eaedf045f142e  # [win and x86_64]

build:
  number: 0
  script:
    - if: unix
      then:
        - |
          case "${target_platform:-}" in
            linux-64)      WHL_FILE="iterfzf-1.8.0.62.0-py3-none-manylinux_1_2_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl" ;;
            linux-aarch64) WHL_FILE="iterfzf-1.8.0.62.0-py3-none-manylinux_1_2_aarch64.manylinux_2_17_aarch64.manylinux2014_aarch64.whl" ;;
            osx-64)        WHL_FILE="iterfzf-1.8.0.62.0-py3-none-macosx_10_7_x86_64.macosx_10_9_x86_64.whl" ;;
            osx-arm64)     WHL_FILE="iterfzf-1.8.0.62.0-py3-none-macosx_11_0_arm64.whl" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          python -m pip install "$SRC_DIR/$WHL_FILE" -vv --no-deps --no-index
    - if: win
      then:
        - python -m pip install %SRC_DIR%\iterfzf-1.8.0.62.0-py3-none-win_amd64.whl -vv --no-deps --no-index

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

tests:
  - python:
      imports:
        - iterfzf
  - script:
      - if: unix
        then:
          - python -c "from iterfzf import iterfzf; print('iterfzf imported successfully')"

about:
  homepage: https://github.com/dahlia/iterfzf
  license: GPL-3.0-or-later
  license_family: GPL
  summary: Pythonic interface to fzf, a command-line fuzzy finder
  description: |
    iterfzf is a Python library providing a Pythonic interface to fzf,
    the command-line fuzzy finder. It bundles prebuilt fzf binaries
    for each platform, so no separate fzf installation is required.

    Key features:
    - Simple Pythonic API for fuzzy selection
    - Bundled fzf binaries for all major platforms
    - Supports iterables and generators as input
    - Multi-select mode support
    - Customizable preview and key bindings
  documentation: https://github.com/dahlia/iterfzf#readme
  repository: https://github.com/dahlia/iterfzf

extra:
  recipe-maintainers:
    - blooop
