schema_version: 1

package:
  name: iterfzf
  version: "1.9.0.67.0"

source:
  # Platform-specific wheels from PyPI (iterfzf bundles fzf binaries)
  - url: https://files.pythonhosted.org/packages/b3/04/be83ea9b5340e4f9f14fd8ef8a42ecb4eb99ef05366673c33b734920b510/iterfzf-1.9.0.67.0-py3-none-manylinux_1_2_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl  # [linux and x86_64]
    sha256: f84da7c420a2c7f4601d0f1c2390b09e06d4981e8c40a8e6f990e83de9871c95  # [linux and x86_64]
  - url: https://files.pythonhosted.org/packages/7d/d1/97c18aaefdcd7a1bb205900e1685d6de02e26c1dda7442f4c34e23837d25/iterfzf-1.9.0.67.0-py3-none-manylinux_1_2_aarch64.manylinux_2_17_aarch64.manylinux2014_aarch64.whl  # [linux and aarch64]
    sha256: 34173f018b7607817dcdc08d26162d972f4296d1b205478118ce0d44e1bf955d  # [linux and aarch64]
  - url: https://files.pythonhosted.org/packages/58/65/a39b5616f37159e45bb0a022b6f33b1de7c828a2862f0a1bdf9a1c33a8ff/iterfzf-1.9.0.67.0-py3-none-macosx_10_7_x86_64.macosx_10_9_x86_64.whl  # [osx and x86_64]
    sha256: a2f75b362f7b99587cc18e4f38d77371399a27050aa2cc77fd2d62e5d815325a  # [osx and x86_64]
  - url: https://files.pythonhosted.org/packages/c6/15/5bed29959f6230003ff8a476a903f273c94e46bb57ee70422d36729af49d/iterfzf-1.9.0.67.0-py3-none-macosx_11_0_arm64.whl  # [osx and arm64]
    sha256: 2463c2001f2e2b2bf7acb5104783da7a5dfe2421e78f56a1c1ee47c7aab297de  # [osx and arm64]
  - url: https://files.pythonhosted.org/packages/7c/ac/a64707d03e1d4e55401535461b9248c91e834b19d8233f40e870495dd54d/iterfzf-1.9.0.67.0-py3-none-win_amd64.whl  # [win and x86_64]
    sha256: 7b4ad3cc6a2e395970be81fb913840ff482b6d9938ecec605e4a6fce9db936fb  # [win and x86_64]

build:
  number: 0
  script:
    - if: unix
      then:
        - |
          case "${target_platform:-}" in
            linux-64)      WHL_FILE="iterfzf-1.9.0.67.0-py3-none-manylinux_1_2_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl" ;;
            linux-aarch64) WHL_FILE="iterfzf-1.9.0.67.0-py3-none-manylinux_1_2_aarch64.manylinux_2_17_aarch64.manylinux2014_aarch64.whl" ;;
            osx-64)        WHL_FILE="iterfzf-1.9.0.67.0-py3-none-macosx_10_7_x86_64.macosx_10_9_x86_64.whl" ;;
            osx-arm64)     WHL_FILE="iterfzf-1.9.0.67.0-py3-none-macosx_11_0_arm64.whl" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          python -m pip install "$SRC_DIR/$WHL_FILE" -vv --no-deps --no-index
    - if: win
      then:
        - python -m pip install %SRC_DIR%\iterfzf-1.9.0.67.0-py3-none-win_amd64.whl -vv --no-deps --no-index

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

tests:
  - python:
      imports:
        - iterfzf
  - script:
      - if: unix
        then:
          - python -c "from iterfzf import iterfzf; print('iterfzf imported successfully')"

about:
  homepage: https://github.com/dahlia/iterfzf
  license: GPL-3.0-or-later
  license_family: GPL
  summary: Pythonic interface to fzf, a command-line fuzzy finder
  description: |
    iterfzf is a Python library providing a Pythonic interface to fzf,
    the command-line fuzzy finder. It bundles prebuilt fzf binaries
    for each platform, so no separate fzf installation is required.

    Key features:
    - Simple Pythonic API for fuzzy selection
    - Bundled fzf binaries for all major platforms
    - Supports iterables and generators as input
    - Multi-select mode support
    - Customizable preview and key bindings
  documentation: https://github.com/dahlia/iterfzf#readme
  repository: https://github.com/dahlia/iterfzf

extra:
  recipe-maintainers:
    - blooop
