schema_version: 1

package:
  name: devpod-prerelease
  version: "0.12.0"

source:
  # NOTE: Using skevetter's fork of devpod from https://github.com/skevetter/devpod/releases
  # This package tracks PRE-RELEASE versions (prerelease: true in GitHub)
  # For stable releases, use the 'devpod' package instead
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.0/devpod-linux-amd64  # [linux and x86_64]
    sha256: b687e9e71d6190ab2e16b69ebd9fc82d958a97989f79d31ccfe272165748571f  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.0/devpod-linux-arm64  # [linux and aarch64]
    sha256: 3c6ed3be6e9e6a47377fbdaf3132fe76e6887ef43a662f3efbd487415bded16f  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.0/devpod-darwin-amd64  # [osx and x86_64]
    sha256: fdf9a3aa04e0a95cb89dab3a157dd586da660c9d30f7f938d120542933b36800  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.0/devpod-darwin-arm64  # [osx and arm64]
    sha256: dc915d2ef4ba8dbb2d6aff3fd569328729b16db520d2cb0de125b0223e5cc8e1  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.0/devpod-windows-amd64.exe  # [win]
    sha256: 9246540c8ec7757b530d1115f1b12d34827b91cfd89515d7033a31ccc902b7a3  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          cp "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
          chmod 755 "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: DevPod pre-release - Codespaces but open-source, client-only and unopinionated
  description: |
    **PRE-RELEASE VERSION** - This package tracks pre-release versions of DevPod.
    For stable releases, install the 'devpod' package instead.

    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/skevetter/devpod

extra:
  recipe-maintainers:
    - blooop
