schema_version: 1

package:
  name: devpod-prerelease
  version: "0.12.11"

source:
  # NOTE: Using skevetter's fork of devpod from https://github.com/skevetter/devpod/releases
  # This package tracks PRE-RELEASE versions (prerelease: true in GitHub)
  # For stable releases, use the 'devpod' package instead
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.11/devpod-linux-amd64  # [linux and x86_64]
    sha256: 8400e908d36efff39c7b77307c88c01155b38e45653e861042a43cc760304e91  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.11/devpod-linux-arm64  # [linux and aarch64]
    sha256: d51adb855755d2f6be512dd6a784ecf03e7e920ed31e7fe7801ccc93661fe8a1  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.11/devpod-darwin-amd64  # [osx and x86_64]
    sha256: c237520ee417ae7e0d5499abb5c6af7fe831092beec4cdb08be1e64a7e16116f  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.11/devpod-darwin-arm64  # [osx and arm64]
    sha256: e50135b90dc7b7241d469dd0b0510b73936b8338773e60f68bc8bd0785d8b1d6  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.11/devpod-windows-amd64.exe  # [win]
    sha256: d2ac25b2a67bed64871a9790b13715440af3b0ee60fb6590456be6c6826dc8dd  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          cp "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
          chmod 755 "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: DevPod pre-release - Codespaces but open-source, client-only and unopinionated
  description: |
    **PRE-RELEASE VERSION** - This package tracks pre-release versions of DevPod.
    For stable releases, install the 'devpod' package instead.

    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/skevetter/devpod

extra:
  recipe-maintainers:
    - blooop
