schema_version: 1

package:
  name: devpod-prerelease
  version: "0.9.11"

source:
  # NOTE: Using skevetter's fork of devpod from https://github.com/skevetter/devpod/releases
  # This package tracks PRE-RELEASE versions (prerelease: true in GitHub)
  # For stable releases, use the 'devpod' package instead
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.11/devpod-linux-amd64  # [linux and x86_64]
    sha256: 6987bb34a0a227e0798e1742e8221297224212451185180b2d55d0b90e7412bb  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.11/devpod-linux-arm64  # [linux and aarch64]
    sha256: 8d27da182757904b3cf40da4a66a8d948050179c7d0b0977790f1b84b9aea229  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.11/devpod-darwin-amd64  # [osx and x86_64]
    sha256: b6d1f51c130d17bf9579a069d33dd17a2a628895074ac023d05b4f2f6b8ef39b  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.11/devpod-darwin-arm64  # [osx and arm64]
    sha256: 648bdebfa98a3265c4982b6b4a2ca271cc5ade67580878cd235d6bc65324b44f  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.11/devpod-windows-amd64.exe  # [win]
    sha256: bca73bd94d444db101cc95dde2766a14299a224601ac32b4a67e368f84d31bcb  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          cp "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
          chmod 755 "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: DevPod pre-release - Codespaces but open-source, client-only and unopinionated
  description: |
    **PRE-RELEASE VERSION** - This package tracks pre-release versions of DevPod.
    For stable releases, install the 'devpod' package instead.

    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/skevetter/devpod

extra:
  recipe-maintainers:
    - blooop
