schema_version: 1

package:
  name: ralph-orchestrator
  version: "2.4.1"

source:
  - if: linux and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.1/ralph-cli-x86_64-unknown-linux-gnu.tar.xz
      sha256: 88f497bd02e9e10a68b22aa6e29b7ff88ec7d63798c6f401338728ce1bf4a7b4
  - if: linux and aarch64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.1/ralph-cli-aarch64-unknown-linux-gnu.tar.xz
      sha256: b43331ce1cd7125486af53f5613755e29c67fa7b2e1d10e23e9d44df62bc373a
  - if: osx and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.1/ralph-cli-x86_64-apple-darwin.tar.xz
      sha256: 39eb68ecd81ef244c4aa8c23d9c037f01c7426ffec9cc9c2ad1d7465a8ba0578
  - if: osx and arm64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.1/ralph-cli-aarch64-apple-darwin.tar.xz
      sha256: 06dbed263e0cdaa5a2d53412794082323607f896de96c41c21ff4c4eb75cc572

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - cp "$SRC_DIR/ralph" "$PREFIX/bin/ralph"
        - chmod 755 "$PREFIX/bin/ralph"

tests:
  - script:
      - if: unix
        then:
          - which ralph
          - test -x $PREFIX/bin/ralph
          - |
              if "$PREFIX/bin/ralph" --version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi

about:
  homepage: https://github.com/mikeyobrien/ralph-orchestrator
  license: MIT
  license_family: MIT
  summary: Hat-based orchestration framework that keeps AI agents in a loop until done
  description: |
    Ralph Orchestrator implements the Ralph Wiggum technique for autonomous AI-driven
    development, enabling continuous iteration on tasks until completion.

    Key features:
    - Multi-backend support (Claude Code, Kiro, Gemini CLI, Codex, and more)
    - Specialized agent personas coordinating via events
    - Quality gates that enforce testing and linting standards
    - Persistent memory and task tracking
    - 31 preset configurations for different workflows
  documentation: https://github.com/mikeyobrien/ralph-orchestrator#readme
  repository: https://github.com/mikeyobrien/ralph-orchestrator

extra:
  recipe-maintainers:
    - blooop
