schema_version: 1

package:
  name: ralph-orchestrator
  version: "2.2.5"

source:
  - if: linux and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.2.5/ralph-cli-x86_64-unknown-linux-gnu.tar.xz
      sha256: 979221c9db2ae45a826ca6e430c217268de27791ee4591d2faed27bd9eebfbd9
  - if: linux and aarch64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.2.5/ralph-cli-aarch64-unknown-linux-gnu.tar.xz
      sha256: 78d75a848ea37e3382a7c98260ec96741ecd298e7085b492fb805ba7443288d6
  - if: osx and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.2.5/ralph-cli-x86_64-apple-darwin.tar.xz
      sha256: 16e35287580547a8733099f9ef8e96ba09a630fc3178535c4dbe8f118fc23833
  - if: osx and arm64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.2.5/ralph-cli-aarch64-apple-darwin.tar.xz
      sha256: b81ff500aedd7f12a42d832037631faa9e432d3eee341b1d2c4471d414e62f7e

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - install -Dm755 "$SRC_DIR/ralph" "$PREFIX/bin/ralph"

tests:
  - script:
      - if: unix
        then:
          - which ralph
          - test -x $PREFIX/bin/ralph
          - |
              if "$PREFIX/bin/ralph" --version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi

about:
  homepage: https://github.com/mikeyobrien/ralph-orchestrator
  license: MIT
  license_family: MIT
  summary: Hat-based orchestration framework that keeps AI agents in a loop until done
  description: |
    Ralph Orchestrator implements the Ralph Wiggum technique for autonomous AI-driven
    development, enabling continuous iteration on tasks until completion.

    Key features:
    - Multi-backend support (Claude Code, Kiro, Gemini CLI, Codex, and more)
    - Specialized agent personas coordinating via events
    - Quality gates that enforce testing and linting standards
    - Persistent memory and task tracking
    - 31 preset configurations for different workflows
  documentation: https://github.com/mikeyobrien/ralph-orchestrator#readme
  repository: https://github.com/mikeyobrien/ralph-orchestrator

extra:
  recipe-maintainers:
    - blooop
