schema_version: 1

package:
  name: ralph-orchestrator
  version: "2.6.0"

source:
  - if: linux and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.6.0/ralph-cli-x86_64-unknown-linux-gnu.tar.xz
      sha256: 21a8a15cab809925677b33fba33ea9eac653d73a4b0fb8f2d0299ec04e4abfc9
  - if: linux and aarch64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.6.0/ralph-cli-aarch64-unknown-linux-gnu.tar.xz
      sha256: 4a721d10b1f1a66ecbca5f61b8c310ed14013660bba83e9cbc4696953c247db0
  - if: osx and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.6.0/ralph-cli-x86_64-apple-darwin.tar.xz
      sha256: 6727bf17afb27b608c15f05cb31e8d30747aa9e444c991929af9e570d6a1965f
  - if: osx and arm64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.6.0/ralph-cli-aarch64-apple-darwin.tar.xz
      sha256: 863aa358d8f1a870df427043f82e4e89cdb2cc9c20314485bef8ff644960d3fb

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - cp "$SRC_DIR/ralph" "$PREFIX/bin/ralph"
        - chmod 755 "$PREFIX/bin/ralph"

tests:
  - script:
      - if: unix
        then:
          - which ralph
          - test -x $PREFIX/bin/ralph
          - |
              if "$PREFIX/bin/ralph" --version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi

about:
  homepage: https://github.com/mikeyobrien/ralph-orchestrator
  license: MIT
  license_family: MIT
  summary: Hat-based orchestration framework that keeps AI agents in a loop until done
  description: |
    Ralph Orchestrator implements the Ralph Wiggum technique for autonomous AI-driven
    development, enabling continuous iteration on tasks until completion.

    Key features:
    - Multi-backend support (Claude Code, Kiro, Gemini CLI, Codex, and more)
    - Specialized agent personas coordinating via events
    - Quality gates that enforce testing and linting standards
    - Persistent memory and task tracking
    - 31 preset configurations for different workflows
  documentation: https://github.com/mikeyobrien/ralph-orchestrator#readme
  repository: https://github.com/mikeyobrien/ralph-orchestrator

extra:
  recipe-maintainers:
    - blooop
