schema_version: 1

package:
  name: ralph-orchestrator
  version: "2.4.4"

source:
  - if: linux and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.4/ralph-cli-x86_64-unknown-linux-gnu.tar.xz
      sha256: 6ac4aa9b9c4a689e767ca2602ad84826a864b51df00928122f014a660bf6b7fc
  - if: linux and aarch64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.4/ralph-cli-aarch64-unknown-linux-gnu.tar.xz
      sha256: 08e6a32900dae3f48dad03c9f7490598d172aefa0bf2175392f9687927cb6aba
  - if: osx and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.4/ralph-cli-x86_64-apple-darwin.tar.xz
      sha256: 938c5397be5731f8562661cf4a47aa48cab1f4420525b08d6643d74ca655052e
  - if: osx and arm64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.4.4/ralph-cli-aarch64-apple-darwin.tar.xz
      sha256: 3ecd8d3aa05bc3e0a494d7fe3dfce22169053799b4f43c5da8be4b36c6bf974b

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - cp "$SRC_DIR/ralph" "$PREFIX/bin/ralph"
        - chmod 755 "$PREFIX/bin/ralph"

tests:
  - script:
      - if: unix
        then:
          - which ralph
          - test -x $PREFIX/bin/ralph
          - |
              if "$PREFIX/bin/ralph" --version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi

about:
  homepage: https://github.com/mikeyobrien/ralph-orchestrator
  license: MIT
  license_family: MIT
  summary: Hat-based orchestration framework that keeps AI agents in a loop until done
  description: |
    Ralph Orchestrator implements the Ralph Wiggum technique for autonomous AI-driven
    development, enabling continuous iteration on tasks until completion.

    Key features:
    - Multi-backend support (Claude Code, Kiro, Gemini CLI, Codex, and more)
    - Specialized agent personas coordinating via events
    - Quality gates that enforce testing and linting standards
    - Persistent memory and task tracking
    - 31 preset configurations for different workflows
  documentation: https://github.com/mikeyobrien/ralph-orchestrator#readme
  repository: https://github.com/mikeyobrien/ralph-orchestrator

extra:
  recipe-maintainers:
    - blooop
