schema_version: 1

package:
  name: ralph-orchestrator
  version: "2.5.1"

source:
  - if: linux and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.5.1/ralph-cli-x86_64-unknown-linux-gnu.tar.xz
      sha256: 164bec3615f147bafa565f9dca7dfa7bb1173f20c1c7a68c5898aeb6c6504466
  - if: linux and aarch64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.5.1/ralph-cli-aarch64-unknown-linux-gnu.tar.xz
      sha256: c2b7ef355bf70cea8579329d0ab981671c41277d4b8de1cfced09fb1245e1402
  - if: osx and x86_64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.5.1/ralph-cli-x86_64-apple-darwin.tar.xz
      sha256: f946815087ae2a1c1f34ebbf268ed3d3603108ef98762a6b9a4789a4363d5a97
  - if: osx and arm64
    then:
      url: https://github.com/mikeyobrien/ralph-orchestrator/releases/download/v2.5.1/ralph-cli-aarch64-apple-darwin.tar.xz
      sha256: 6c6d8d74d1b1a08e85901defd997711cd04f7d7f4c9d28ebf32fb7b5c142689f

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - cp "$SRC_DIR/ralph" "$PREFIX/bin/ralph"
        - chmod 755 "$PREFIX/bin/ralph"

tests:
  - script:
      - if: unix
        then:
          - which ralph
          - test -x $PREFIX/bin/ralph
          - |
              if "$PREFIX/bin/ralph" --version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi

about:
  homepage: https://github.com/mikeyobrien/ralph-orchestrator
  license: MIT
  license_family: MIT
  summary: Hat-based orchestration framework that keeps AI agents in a loop until done
  description: |
    Ralph Orchestrator implements the Ralph Wiggum technique for autonomous AI-driven
    development, enabling continuous iteration on tasks until completion.

    Key features:
    - Multi-backend support (Claude Code, Kiro, Gemini CLI, Codex, and more)
    - Specialized agent personas coordinating via events
    - Quality gates that enforce testing and linting standards
    - Persistent memory and task tracking
    - 31 preset configurations for different workflows
  documentation: https://github.com/mikeyobrien/ralph-orchestrator#readme
  repository: https://github.com/mikeyobrien/ralph-orchestrator

extra:
  recipe-maintainers:
    - blooop
