context:
  version: "0.1.0"

package:
  name: ros-jazzy-phantom-touch-description
  version: ${{ version }}

source:
  git: https://github.com/kinisi-robotics/phantom_touch_ros2.git
  rev: 2bf5b20f26071646423656915506e7c18fa97c07
  target_directory: ros-jazzy-phantom-touch-description/src/work

build:
  number: 0
  script: build_ament_python.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - cmake
    - ninja
    - python
    - pkg-config
  host:
    - python
    - pip
    - ros-jazzy-ament-cmake
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
  run:
    - python
    - ros-jazzy-ros-workspace
    - ros-jazzy-xacro
    - ros-jazzy-robot-state-publisher

tests:
  - script:
      - test -d $PREFIX/share/phantom_touch_description

about:
  homepage: https://github.com/kinisi-robotics/phantom_touch_ros2
  summary: "URDF description for Phantom Touch haptic device"
  license: LicenseRef-Proprietary
