schema_version: 1

package:
  name: pkl
  version: "0.31.0"

source:
  - url: https://github.com/apple/pkl/releases/download/0.31.0/pkl-linux-amd64  # [linux and x86_64]
    sha256: 5a5c2a889b68ca92ff4258f9d277f92412b98dfef5057daef7564202a20870b6  # [linux and x86_64]
  - url: https://github.com/apple/pkl/releases/download/0.31.0/pkl-linux-aarch64  # [linux and aarch64]
    sha256: 471460cdd11e1cb9ac0a5401fdb05277ae3adb3a4573cc0a9c63ee087c1f93c8  # [linux and aarch64]
  - url: https://github.com/apple/pkl/releases/download/0.31.0/pkl-macos-amd64  # [osx and x86_64]
    sha256: 9f1cc8e3ac2327bc483b90d0c220da20eb785c3ba3fe92e021f47d3d56768282  # [osx and x86_64]
  - url: https://github.com/apple/pkl/releases/download/0.31.0/pkl-macos-aarch64  # [osx and arm64]
    sha256: 349402ae32c35382c034b0c0af744ffb0d53a213888c44deec94a7810e144889  # [osx and arm64]
  - url: https://github.com/apple/pkl/releases/download/0.31.0/pkl-windows-amd64.exe  # [win]
    sha256: 37d35ce8a165766502fb13799071d4cefa84d39fb455c75c471b47b9b5d12b04  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="pkl-linux-amd64" ;;
            linux-aarch64) SRC_FILE="pkl-linux-aarch64" ;;
            osx-64)        SRC_FILE="pkl-macos-amd64" ;;
            osx-arm64)     SRC_FILE="pkl-macos-aarch64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          cp "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/pkl"
          chmod 755 "$PREFIX/bin/pkl"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\pkl-windows-amd64.exe %PREFIX%\Library\bin\pkl.exe

tests:
  - script:
      - if: unix
        then:
          - which pkl
          - test -x $PREFIX/bin/pkl
          - pkl --version
      - if: win
        then:
          - where pkl
          - pkl --version

about:
  homepage: https://pkl-lang.org
  license: Apache-2.0
  license_family: APACHE
  summary: A configuration as code language with rich validation and tooling
  description: |
    Pkl is a configuration-as-code language designed with built-in validation
    and comprehensive tooling support. It enables developers to define
    configurations programmatically with strong type checking and validation
    capabilities. Pkl can generate configuration in multiple formats including
    JSON, YAML, XML, and property files.
  documentation: https://pkl-lang.org/main/current/
  repository: https://github.com/apple/pkl

extra:
  recipe-maintainers:
    - blooop
