schema_version: 1

package:
  name: claude-shim
  version: "0.4.0"

source:
  - path: claude-shim.sh
  - path: cld.sh
  - path: cldr.sh

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin
    - cp $SRC_DIR/claude-shim.sh $PREFIX/bin/claude
    - cp $SRC_DIR/cld.sh $PREFIX/bin/cld
    - cp $SRC_DIR/cldr.sh $PREFIX/bin/cldr
    - chmod +x $PREFIX/bin/claude $PREFIX/bin/cld $PREFIX/bin/cldr

requirements:
  run: []

tests:
  - script:
      - if: unix
        then:
          - which claude
          - which cld
          - which cldr
          - test -x $PREFIX/bin/claude
          - test -x $PREFIX/bin/cld
          - test -x $PREFIX/bin/cldr
          - bash -n $PREFIX/bin/claude  # syntax check
          - bash -n $PREFIX/bin/cld
          - bash -n $PREFIX/bin/cldr
      - if: win
        then:
          - where claude
          - where cld
          - where cldr

about:
  homepage: https://claude.ai/
  license: LicenseRef-Proprietary
  license_family: Proprietary
  summary: Claude Code installer shim - downloads and runs the official Claude Code CLI
  description: |
    This package provides a shim that downloads and runs the official Claude Code
    CLI from Anthropic. It exposes the following commands:
    - 'claude' - the main Claude Code CLI
    - 'cld' - shortcut for 'claude --dangerously-skip-permissions'
    - 'cldr' - shortcut for 'claude --dangerously-skip-permissions --resume'

    Behavior:
    - If Claude is already installed via the official installer (~/.local/bin/claude),
      the shim defers to it, ensuring compatibility with existing installations.
    - If no official installation exists, the shim downloads the stable Claude Code
      release on first run.
    - Updates are downloaded in the background so you can start working immediately.
    - The new version is swapped in on the next invocation.
    - Supports Docker caching: mount ~/.claude or ~/.cache to persist downloads
      across container runs.
    - Self-healing: automatically detects and repairs corrupted cached binaries.

    Cache directory priority:
    1. ~/.claude/cache/claude-code (if ~/.claude exists)
    2. ~/.cache/claude-code (if ~/.cache exists)
    3. ${CONDA_PREFIX}/opt/claude-code (fallback)

    This package does NOT redistribute Claude Code to comply with licensing
    requirements. It only downloads from Anthropic's official distribution servers.

    Claude Code is a CLI tool that provides AI-powered coding assistance
    from Anthropic's Claude AI models.
  documentation: https://docs.anthropic.com/en/docs/claude-code
  repository: https://github.com/anthropics/claude-code

extra:
  recipe-maintainers:
    - blooop
