schema_version: 1

package:
  name: devpod
  version: "0.8.11"

source:
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.11/devpod-linux-amd64  # [linux and x86_64]
    sha256: 3af43f6aee2de808289aa923ad7daa21f748a8991031f8d1313c658b7c043f7f  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.11/devpod-linux-arm64  # [linux and aarch64]
    sha256: e5a863d548306c922ba5e9f079bd62e24177fc082da306221e86d901bd2fd799  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.11/devpod-darwin-amd64  # [osx and x86_64]
    sha256: 5cad702513a5cf47c7f0b6b60a1ac835c6f90e1c6598cb47a3a572ccc9453949  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.11/devpod-darwin-arm64  # [osx and arm64]
    sha256: 0964aef49aba9aeea0e2665e2a930d8a0bad8c163302314073a8d3cf6ed0ca7c  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.11/devpod-windows-amd64.exe  # [win]
    sha256: 6e618cca2a6e8fc8b774391281dca0251589455c5398b55a576e53e598154a0e  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          install -Dm755 "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: Codespaces but open-source, client-only and unopinionated
  description: |
    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/loft-sh/devpod

extra:
  recipe-maintainers:
    - blooop
