schema_version: 1

package:
  name: devpod
  version: "0.12.12"

source:
  # NOTE: Using skevetter's fork of devpod from https://github.com/skevetter/devpod/releases
  # instead of the official devpod (https://github.com/loft-sh/devpod)
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.12/devpod-linux-amd64  # [linux and x86_64]
    sha256: f65aaf3ef7eb5a8c377c2e86a9330562829d3deaec0f8b943134122a89d0fe1e  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.12/devpod-linux-arm64  # [linux and aarch64]
    sha256: 12e3c34a69f0164ba3bdb7be312703dd703e83615a0f6f1a8a44ae1ac37b692c  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.12/devpod-darwin-amd64  # [osx and x86_64]
    sha256: 87bb81a13225754320244a428397c4a3cbfc076c8fbd54cf04d6670858b3cd9c  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.12/devpod-darwin-arm64  # [osx and arm64]
    sha256: 2081727ea08da9fece51529272652692a8267aad6e19063a4e200ef8d13e3449  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.12/devpod-windows-amd64.exe  # [win]
    sha256: 54c8c560c3aaffa4347bff8b88c73155a381a5cc0e852d958dac568c873d0754  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          cp "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
          chmod 755 "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: Codespaces but open-source, client-only and unopinionated
  description: |
    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/skevetter/devpod

extra:
  recipe-maintainers:
    - blooop
