schema_version: 1

package:
  name: devpod
  version: "0.9.1"

source:
  # NOTE: Using skevetter's fork of devpod from https://github.com/skevetter/devpod/releases
  # instead of the official devpod (https://github.com/loft-sh/devpod)
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.1/devpod-linux-amd64  # [linux and x86_64]
    sha256: 57891dc3d13379366aa20602ba8bbf144a357907565db3b570a30602b1baf780  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.1/devpod-linux-arm64  # [linux and aarch64]
    sha256: 0e5feaca09abefc1baf545ba18579bdcb335f9b110a264a14eb2876ed31e7450  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.1/devpod-darwin-amd64  # [osx and x86_64]
    sha256: 414b810a563bf8376c260cc42946737eaa1b60d89239c7413362f33052ebdf55  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.1/devpod-darwin-arm64  # [osx and arm64]
    sha256: 3c1c43dea4943bc1d8484ea2255d57c583151a0a73468537f6534b43f893b30b  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.9.1/devpod-windows-amd64.exe  # [win]
    sha256: a23d7c9f6a72d95fa3a2cd8b2584272bfb0d72a165d04d7b1c731a17a41f341b  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          install -Dm755 "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: Codespaces but open-source, client-only and unopinionated
  description: |
    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/skevetter/devpod

extra:
  recipe-maintainers:
    - blooop
