schema_version: 1

package:
  name: devpod
  version: "0.8.12"

source:
  # NOTE: Using skevetter's fork of devpod from https://github.com/skevetter/devpod/releases
  # instead of the official devpod (https://github.com/loft-sh/devpod)
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.12/devpod-linux-amd64  # [linux and x86_64]
    sha256: 1ad3db0434b7881ccf457272e2b8a086f9d8279e3c34cfce8bf9983f8b6b93af  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.12/devpod-linux-arm64  # [linux and aarch64]
    sha256: c01e29dfe318164ba807e3f281f92ad4d801a5448752fca544244f12e8e4f8bf  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.12/devpod-darwin-amd64  # [osx and x86_64]
    sha256: 63634e5052136365cf0404394d90958b0e86bd5d9de949e8371dd79dab6cb2b4  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.12/devpod-darwin-arm64  # [osx and arm64]
    sha256: 60d572dc2a8eddd3819fe0ce784e5e908cf1796b0a7ef1a86084621d5a6d0485  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.8.12/devpod-windows-amd64.exe  # [win]
    sha256: da0e6d9372b1e472a042c5f36adcb7dec8867e0a17c65686c0321525286f9681  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          install -Dm755 "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: Codespaces but open-source, client-only and unopinionated
  description: |
    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/skevetter/devpod

extra:
  recipe-maintainers:
    - blooop
