schema_version: 1

package:
  name: devpod
  version: "0.12.7"

source:
  # NOTE: Using skevetter's fork of devpod from https://github.com/skevetter/devpod/releases
  # instead of the official devpod (https://github.com/loft-sh/devpod)
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.7/devpod-linux-amd64  # [linux and x86_64]
    sha256: 42402a5d43e43b9e6d6ef77acf325cfb81e0253a1b98766bde0697f4b760de6d  # [linux and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.7/devpod-linux-arm64  # [linux and aarch64]
    sha256: 9d318764a711b90597baec79d3d836319adf47f05915c87389a1a2786800d1f5  # [linux and aarch64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.7/devpod-darwin-amd64  # [osx and x86_64]
    sha256: 83e78380b167be36a0ef2d668d5d0e281af3fcd6792081123d280897c0353b56  # [osx and x86_64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.7/devpod-darwin-arm64  # [osx and arm64]
    sha256: a6c6d17b85090cf38e3e747848c2dad3f6b81647d4e199765066a80916fed4c0  # [osx and arm64]
  - url: https://github.com/skevetter/devpod/releases/download/v0.12.7/devpod-windows-amd64.exe  # [win]
    sha256: 29fd82e8fb3e2d16b5458a554ff5adcce97a2e4ea0970f8d3023dfe7152d7218  # [win]

build:
  number: 0
  script:
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - |
          case "${target_platform:-}" in
            linux-64)      SRC_FILE="devpod-linux-amd64" ;;
            linux-aarch64) SRC_FILE="devpod-linux-arm64" ;;
            osx-64)        SRC_FILE="devpod-darwin-amd64" ;;
            osx-arm64)     SRC_FILE="devpod-darwin-arm64" ;;
            *) echo "Unsupported target_platform: ${target_platform:-unknown}" && exit 1 ;;
          esac
          cp "$SRC_DIR/$SRC_FILE" "$PREFIX/bin/devpod"
          chmod 755 "$PREFIX/bin/devpod"
    - if: win
      then:
        - if not exist %PREFIX%\Library\bin mkdir %PREFIX%\Library\bin
        - copy %SRC_DIR%\devpod-windows-amd64.exe %PREFIX%\Library\bin\devpod.exe

tests:
  - script:
      - if: unix
        then:
          - which devpod
          - test -x $PREFIX/bin/devpod
          - |
              if "$PREFIX/bin/devpod" version; then
                :
              else
                status=$?
                if [ "$status" -eq 126 ]; then
                  echo "Skipping runtime test for non-native binary on $(uname -m)"
                else
                  exit "$status"
                fi
              fi
      - if: win
        then:
          - where devpod
          - devpod version

about:
  homepage: https://devpod.sh
  license: MPL-2.0
  license_family: MOZILLA
  summary: Codespaces but open-source, client-only and unopinionated
  description: |
    DevPod is an open-source tool that allows you to create reproducible developer
    environments based on a devcontainer.json on any backend. Each developer environment
    runs in a separate container and is specified through a devcontainer.json.

    DevPod can use any IDE and works with any cloud provider, Kubernetes cluster,
    or on localhost. It's designed to be a cost-effective alternative to GitHub
    Codespaces and similar hosted services.

    Key features:
    - Support for multiple IDEs (VSCode, JetBrains, and more)
    - Works with various backends (Docker, Kubernetes, SSH, cloud VMs)
    - DevContainer standard compliant
    - Client-only architecture for maximum privacy and control
  documentation: https://devpod.sh/docs
  repository: https://github.com/skevetter/devpod

extra:
  recipe-maintainers:
    - blooop
