schema_version: 1

context:
  version: "1.6.0"

package:
  name: ethercat-user
  version: ${{ version }}

source:
  git: https://gitlab.com/etherlab.org/ethercat.git
  rev: stable-1.6
  patches:
    - ethercat_reset.patch

build:
  number: 0
  skip:
    - not linux
  script:
    - |
      autoupdate || true
      autoreconf -fi
      ./bootstrap

      ./configure \
          --prefix="$PREFIX" \
          --disable-kernel \
          --disable-8139too \
          --disable-eoe \
          --enable-generic

      make -j"${CPU_COUNT}"
      make install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config

tests:
  - script:
      - test -f $PREFIX/include/ecrt.h
      - test -f $PREFIX/lib/libethercat.so

about:
  homepage: https://etherlab.org/en/ethercat/
  license: GPL-2.0-only
  license_family: GPL
  summary: EtherCAT user-space library (no kernel module)
  description: |
    IgH EtherCAT Master user-space library, built without kernel module support.
    Provides the libethercat library and ecrt.h header for EtherCAT communication.
    Includes a patch adding ecrt_master_set_slave_state() for slave state management.
  repository: https://gitlab.com/etherlab.org/ethercat

extra:
  recipe-maintainers:
    - blooop
