schema_version: 1

package:
  name: claude-code
  version: "2.1.3"

source:
  - path: claude-shim.sh

build:
  number: 1
  script:
    - mkdir -p $PREFIX/bin
    - cp $SRC_DIR/claude-shim.sh $PREFIX/bin/claude
    - chmod +x $PREFIX/bin/claude

requirements:
  run: []

tests:
  - script:
      - if: unix
        then:
          - which claude
          - test -x $PREFIX/bin/claude
          - bash -n $PREFIX/bin/claude  # syntax check
      - if: win
        then:
          - where claude

about:
  homepage: https://claude.ai/
  license: LicenseRef-Proprietary
  license_family: Proprietary
  summary: Claude AI coding assistant installer shim
  description: |
    This package provides a shim that integrates with the official Claude Code
    application from Anthropic. It exposes the 'claude' command.

    Behavior:
    - If Claude is already installed via the official installer (~/.local/bin/claude),
      the shim defers to it, ensuring compatibility with existing installations.
    - If no official installation exists, the shim downloads the latest Claude Code
      on first run to the conda/pixi environment.
    - The shim auto-updates to the latest stable version when available.

    This package does NOT redistribute Claude Code to comply with licensing
    requirements. It only downloads from Anthropic's official distribution servers.

    Claude Code is a CLI tool that provides AI-powered coding assistance
    from Anthropic's Claude AI models.
  documentation: https://claude.ai/docs
  repository: https://claude.ai/

extra:
  recipe-maintainers:
    - blooop
