schema_version: 1

package:
  name: claude-code
  version: "2.1.3"

source:
  - path: claude-shim.sh

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin
    - cp $SRC_DIR/claude-shim.sh $PREFIX/bin/claude-code
    - chmod +x $PREFIX/bin/claude-code

requirements:
  run: []

tests:
  - script:
      - if: unix
        then:
          - which claude-code
          - test -x $PREFIX/bin/claude-code
          - bash -n $PREFIX/bin/claude-code  # syntax check
      - if: win
        then:
          - where claude-code

about:
  homepage: https://claude.ai/
  license: LicenseRef-Proprietary
  license_family: Proprietary
  summary: Claude AI coding assistant installer shim
  description: |
    This package provides a shim that downloads and runs the official Claude Code
    binary from Anthropic on first run. This package does NOT redistribute
    Claude Code to comply with licensing requirements.

    On first execution, the shim will automatically download the latest Claude Code
    binary for your platform from Anthropic's official distribution servers and install
    it within your conda/pixi environment. The shim also auto-updates to the latest
    stable version when available.

    Claude Code is a CLI tool that provides AI-powered coding assistance
    from Anthropic's Claude AI models. It offers code editing, explanation,
    debugging help, and other development tools integrated into your terminal workflow.
  documentation: https://claude.ai/docs
  repository: https://claude.ai/

extra:
  recipe-maintainers:
    - blooop
