schema_version: 1

package:
  name: claude-code
  version: "2.0.61"

source:

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin
    - echo "#!/bin/bash" > $PREFIX/bin/claude-code
    - echo "echo 'Claude Code $PKG_VERSION - Demo Package'" >> $PREFIX/bin/claude-code
    - chmod +x $PREFIX/bin/claude-code

requirements:
  build:
    - tar  # [unix]
    - unzip  # [win]

tests:
  - script:
      - claude-code
      - which claude-code

about:
  homepage: https://claude.ai/
  license: LicenseRef-Proprietary
  license_family: Proprietary
  summary: Claude AI coding assistant desktop application
  description: |
    Claude Code is a desktop application that provides AI-powered coding assistance
    from Anthropic's Claude AI models. It offers code completion, explanation,
    debugging help, and other development tools integrated into your workflow.
  documentation: https://claude.ai/docs
  repository: https://claude.ai/

extra:
  recipe-maintainers:
    - blooop