context:
  version: "2.0.2"
  commit: "d8d54abda51f10554501854a744f21fd5b63daf6"

package:
  name: ros-jazzy-trac-ik-lib
  version: ${{ version }}

source:
  git: https://bitbucket.org/traclabs/trac_ik.git
  rev: ${{ commit }}
  target_directory: ros-jazzy-trac-ik-lib/src/work

build:
  number: 0
  script: build_ament_cmake.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - cmake
    - ninja
    - python
    - pkg-config
  host:
    - python
    - pip
    - nlopt
    - ros-jazzy-ament-cmake
    - ros-jazzy-eigen3-cmake-module
    - ros-jazzy-geometry-msgs
    - ros-jazzy-kdl-parser
    - ros-jazzy-orocos-kdl-vendor
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-urdf
  run:
    - python
    - nlopt
    - ros-jazzy-ros-workspace
    - ros-jazzy-geometry-msgs
    - ros-jazzy-kdl-parser
    - ros-jazzy-orocos-kdl-vendor
    - ros-jazzy-rclcpp
    - ros-jazzy-urdf

tests:
  - script:
      - test -f $PREFIX/lib/libtrac_ik.so

about:
  homepage: https://bitbucket.org/traclabs/trac_ik
  summary: "TRAC-IK inverse kinematics library for ROS 2 Jazzy"
  license: BSD-3-Clause
