context:
  version: "2.0.2"
  commit: "d8d54abda51f10554501854a744f21fd5b63daf6"

package:
  name: ros-jazzy-trac-ik-kinematics-plugin
  version: ${{ version }}

source:
  git: https://bitbucket.org/traclabs/trac_ik.git
  rev: ${{ commit }}
  target_directory: ros-jazzy-trac-ik-kinematics-plugin/src/work

build:
  number: 0
  script: build_ament_cmake.sh

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - cmake
    - ninja
    - python
    - pkg-config
  host:
    - python
    - pip
    - ros-jazzy-ament-cmake
    - ros-jazzy-class-loader
    - ros-jazzy-generate-parameter-library
    - ros-jazzy-moveit-core
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-ros-environment
    - ros-jazzy-ros-workspace
    - ros-jazzy-tf2-kdl
    - ros-jazzy-trac-ik-lib
    - ros-jazzy-urdf
  run:
    - python
    - ros-jazzy-ros-workspace
    - ros-jazzy-class-loader
    - ros-jazzy-moveit-core
    - ros-jazzy-pluginlib
    - ros-jazzy-rclcpp
    - ros-jazzy-tf2-kdl
    - ros-jazzy-trac-ik-lib
    - ros-jazzy-urdf

tests:
  - script:
      - test -f $PREFIX/lib/libtrac_ik_kinematics_plugin.so

about:
  homepage: https://bitbucket.org/traclabs/trac_ik
  summary: "TRAC-IK MoveIt kinematics plugin for ROS 2 Jazzy"
  license: BSD-3-Clause
